jobs:
  include:
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: hnfhtw-frontend-staging
        api_key: $HEROKU_API_KEY
    - stage: deploy to production
      script: skip
      deploy:
        <<: *heroku
        app: hnfhtw-frontend
    - stage: check production availability
      script: 'curl https://hnfhtw-frontend.herokuapp.com/'
